[package]
name = "libloading"
version = "0.1.0"
authors = ["Simonas Kazlauskas <git@kazlauskas.me>"]

[dependencies.winapi]
git = "http://github.com/retep998/winapi-rs.git"

[dependencies.kernel32-sys]
git = "http://github.com/retep998/winapi-rs.git"
path = "lib/kernel32-sys"

[dependencies.psapi-sys]
git = "http://github.com/retep998/winapi-rs.git"
path = "lib/psapi-sys"
